library(ggplot2)

grp.1 <- read.table("../pvals_psp_aa_norm_tai.txt",sep="",header=0)
grp.2 <- read.table("../pvals_psp_tai.txt",sep="",header=0)
grp.3 <- read.table("../pvals_nosp_aa_norm_tai.txt",sep="",header=0)
grp.4 <- read.table("../pvals_nosp_tai.txt",sep="",header=0)
labels <- c(rep("(d) Simulated Pseudo-Signal Peptides (Amino Acid Usage Consistent with Signal Peptides)",500),rep("(b) Simulated Pseudo-Signal Peptides",500),rep("(c) Simulated 5'-ends (Amino Acid Usage Consistent with Signal Peptides)",500),rep("(a) Simulated 5'-ends (Nonsecretory)",500))
labels_f <- factor(x=labels,levels=c("(a) Simulated 5'-ends (Nonsecretory)","(b) Simulated Pseudo-Signal Peptides","(c) Simulated 5'-ends (Amino Acid Usage Consistent with Signal Peptides)","(d) Simulated Pseudo-Signal Peptides (Amino Acid Usage Consistent with Signal Peptides)"))
df <- rbind(grp.1,grp.2)
df<- rbind(df,grp.3)
df <- rbind(df,grp.4)
df <- cbind(df,labels)
df <- cbind(df,labels_f)
colnames(df) <- c("pvalues","Label","Label_f")


p<-(ggplot(data=df,aes(x=pvalues,color=Label,fill=Label)) + geom_histogram(position="identity",alpha=0.25,breaks=seq(0,1,0.05)) 
+ scale_color_manual(values=c("black","black","black","black"))
+ scale_fill_manual(values=c("black","black","black","black"))
+ggtitle("Comparing tAI of Simulated 5' Regions to Simulated Signal Peptides:\nDistribution of p-values")
+xlab("p-value")
+ylab("Counts")
+scale_x_continuous(labels=seq(0.0,1.0,0.05),breaks=seq(0,1,0.05))
+theme(panel.background = element_blank(),axis.line = element_line(colour = "black"),axis.text = element_text(face = "bold",color="black") ,legend.position = "none",plot.title=element_text(hjust=0.5),legend.title = element_blank())
+ facet_wrap(~Label_f,ncol=1,scales = "free_y"))
ggsave(filename = "pval_tai.pdf",height = 7,width=7)